project:
  type: website
  output-dir: docs        # ← build your HTML into docs/

website:
  title: "Crowbar"       # ← your site title
  page-navigation: true    # ← keep prev/next links
  navbar:
    left:
      - text: Home;        href: index.html
      - text: Writing;     href: writing/index.html
      - text: "Math & Physics"; href: physics/index.html

format:
  html:
    self-contained: true
    toc: true
    html-math-method: mathjax
    page-layout: full
    anchor-sections: true

output:
  html:
    clean-url: true
