name: Build & deploy Quarto site to docs/

on:
  push:
    branches: [ main ]
    # Don’t retrigger when docs/ changes
    paths-ignore:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: quarto render

      - name: Copy .well-known to docs (if exists)
        run: |
          if [ -d .well-known ]; then
            cp -r .well-known docs/
          fi

      - name: Copy _config.yml to docs
        run: cp _config.yml docs/

      - name: Copy modules to docs
        run: cp -r modules docs/

      - name: Commit & push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "🔄 Update built site" || echo "No changes to commit"
          git push origin main
