name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: quarto render

      - name: Copy .well-known to public (if exists)
        run: |
          if [ -d .well-known ]; then
            cp -r .well-known public/
          fi

      - name: Copy _config.yml to public
        run: cp _config.yml public/

      - name: Copy modules to public
        run: cp -r modules public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
